### ISSUE TITLE
Issue in main.py (api) - NEO4J_PASS

### ISSUE THREAD

**Issue by juldla** [neo4j/NaLLM#56]
Hi, I saw that in line 45 of main.py database=os.environ.get("**NEO4J_PASS",** "companies") should be replaced by database=os.environ.get("**NEO4J_DATABASE",** "companies")

neo4j_connection = Neo4jDatabase(
    host=os.environ.get("NEO4J_URL", "neo4j+s://demo.neo4jlabs.com"),
    user=os.environ.get("NEO4J_USER", "companies"),
    password=os.environ.get("NEO4J_PASS", "companies"),
    database=os.environ.get("**NEO4J_PASS",** "companies"),
)

**Comment by tomasonjo** [comment]
Thanks you for reporting the issue. The fix has been merged.
