### ISSUE TITLE
Unable to Access demo.neo4jlabs.com

### ISSUE THREAD

**Issue by lzyxx77** [neo4j/NaLLM#68]
I have run docker-compose up to build the images, and I can open the interface at http://localhost:4173/ where I can see three use cases. However, every time I click on one of them, I am unable to use it, and I also cannot access demo.neo4jlabs.com.
![image](https://github.com/neo4j/NaLLM/assets/94185075/9981d45a-1626-48d0-8cfb-e5486494c423)
for example，I can not  chick Import

**Comment by ahmadien** [comment]
@lzyxx77 I have the same issue, were you able to fix it?

**Comment by lzyxx77** [comment]
> @lzyxx77 I have the same issue, were you able to fix it?

no , thank u

**Comment by jexp** [comment]
Can you access this:
https://demo.neo4jlabs.com:7473/browser/

the bolt URL the app uses should be neo4j://demo.neo4jlabs.com:7687

**Comment by ahmadien** [comment]
I was able to fix the issue with deleting the docker image from my system, then adding the .env inside the UI folder, then building the docker-compose again. It worked fine!
I did not pay attention for the .env file inside the UI folder.

**Comment by lzyxx77** [comment]
> I was able to fix the issue with deleting the docker image from my system, then adding the .env inside the UI folder, then building the docker-compose again. It worked fine! I did not pay attention for the .env file inside the UI folder.

thank you！
