### ISSUE TITLE
ValueError: Missing APOC Core plugin (AuraDB)

### ISSUE THREAD

**Issue by dvirm-cr** [neo4j/NaLLM#70]
Hello, we are trying to use this project on our AuraDB instance,
and get the following 
```ValueError: Missing APOC Core plugin```
which is actually out of the box available on Aura
thank you

**Comment by tomasonjo** [comment]
That happens when the schema cannot be inferred: https://github.com/neo4j/NaLLM/blob/main/api/src/driver/neo4j.py#L69

Can you try running these three queries separately and confirm if they work?

https://github.com/neo4j/NaLLM/blob/main/api/src/driver/neo4j.py#L5

**Comment by dvirm-cr** [comment]
@tomasonjo ty Tomas, I just did
The 3 queries indeed work

**Comment by tomasonjo** [comment]
Can you print the exception here:

https://github.com/neo4j/NaLLM/blob/main/api/src/driver/neo4j.py#L71

**Comment by dvirm-cr** [comment]
@tomasonjo I had a mistake passing the `NEO4J_DATABASE` env var, sorry about that
