### ISSUE TITLE
Can I change the model

### ISSUE THREAD

**Issue by ninghairong** [neo4j/NaLLM#89]
Can I replace the large model used here with the model deployed in Ollama?

**Comment by Satyam7166-tech** [comment]
Same question

**Comment by blacksmithop** [comment]
@ninghairong @Satyam7166-tech the `OpenAIChat` instance is passed here https://github.com/neo4j/NaLLM/blob/1af09cd117ba0777d81075c597a5081583568f9f/api/src/main.py#L80-L88

You can instead define your own `Ollama` model and pass it instead

**Comment by Satyam7166-tech** [comment]
> @ninghairong @Satyam7166-tech the `OpenAIChat` instance is passed here https://github.com/neo4j/NaLLM/blob/1af09cd117ba0777d81075c597a5081583568f9f/api/src/main.py#L80-L88
> 
> 
> 
> You can instead define your own `Ollama` model and pass it instead

Thanks a lot, will do 😃

**Comment by ninghairong** [comment]
Thanks a lot 😀
